import { ARTICLE_EXCEPTION_CODES } from './article';
import { AUTH_EXCEPTION_CODES, JWT_EXCEPTION_CODES, OAUTH_EXCEPTION_CODES } from './auth';
import { SERIES_EXCEPTION_CODES } from './series';

export const EXCEPTION_CODES = {
  ...AUTH_EXCEPTION_CODES,
  ...JWT_EXCEPTION_CODES,
  ...OAUTH_EXCEPTION_CODES,
  ...ARTICLE_EXCEPTION_CODES,
  ...SERIES_EXCEPTION_CODES,
} as const;
