import { AUTH_EXCEPTION_CODES, JWT_EXCEPTION_CODES, OAUTH_EXCEPTION_CODES } from './auth';

export const EXCEPTION_CODES = {
  ...AUTH_EXCEPTION_CODES,
  ...JWT_EXCEPTION_CODES,
  ...OAUTH_EXCEPTION_CODES,
} as const;
