import { ARTICLE_EXCEPTION_CODES } from './article';
import { ARTICLE_COMMENT_EXCEPTION_CODES } from './article-comment';
import { AUTH_EXCEPTION_CODES, JWT_EXCEPTION_CODES, OAUTH_EXCEPTION_CODES } from './auth';
import { SERIES_EXCEPTION_CODES } from './series';

export const EXCEPTION_CODES = {
  ...AUTH_EXCEPTION_CODES,
  ...JWT_EXCEPTION_CODES,
  ...OAUTH_EXCEPTION_CODES,
  ...ARTICLE_EXCEPTION_CODES,
  ...SERIES_EXCEPTION_CODES,
  ...ARTICLE_COMMENT_EXCEPTION_CODES,
} as const;

export type ExceptionCode = keyof typeof EXCEPTION_CODES;
